[tool.poetry]
authors = ["CaptchaRun <admin@captcha.run>"]
description = ""
license = "MIT"
name = "captcharun"
readme = "README.md"
version = "0.2.0"

homepage = "https://captcha.run"
repository = "https://github.com/captcha-run/python-sdk"

classifiers = ["Programming Language :: Python :: 3"]

packages = [{ include = "captcharun" }]

[tool.poetry.dependencies]
python = "^3.7"
httpx = "^0.22.0"

[tool.poetry.dev-dependencies]
black = "*"
isort = "*"
pytest = "*"
pytest-asyncio = "^0.18.3"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
