[tool.poetry]
name = "costack_sdk"
version = "0.1.3"
description = "the sdk to support lambda workflows and seamless integrations"
authors = ["perseus.yang <ry82@cornell.edu>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
