[tool.poetry]
name = "deepspeech-cli"
version = "0.1.5"
description = ""
authors = ["Xinyuan Chen <45612704+tddschn@users.noreply.github.com>"]

[tool.poetry.scripts]
ds = "deepspeech_cli.deepspeech_cli:app"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.4.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
yapf = "^0.32.0"
bump2version = "^1.0.1"
logging-utils-tddschn = "^0.1.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
