[tool.poetry]
name = "lablift-client"
version = "0.1.1"
description = "Access LabLift services using Python"
authors = ["Rafael Bizao <rabizao@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mkdocs-material = "^8.2.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
